version: '2'

services:

  client:
    build: ../tcp-client
    hostname: client
    command:  python3 /build/tcpClient.py example.com 5551
    networks:
      kwic-net:

  server:
    build: ../tcp-server
    hostname: server 
    command : python3 /build/tcpServer.py server 5552
    depends_on:
      - "onprem"
    networks:
      kwic-net:

  pumba:
    image: gaiaadm/pumba
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    command: pumba netem --duration 100m --interface eth1 rate --rate 1500kbit 1simple_onprem_1     


  example.com:
    image: kaazing/enterprise-gateway:5.7.0
    volumes:
      - ./config/cloud-config.xml:/kaazing-gateway/conf/gateway-config.xml:ro
      - ./config/log4j-config.xml:/kaazing-gateway/conf/log4j-config.xml:ro
    ports:
      - "5551:5551"
      - "7771:7771"
    networks:
      kwic-net:

  onprem:
    image: kaazing/enterprise-gateway:5.7.0
    volumes:
      - ./config/onprem-config.xml:/kaazing-gateway/conf/gateway-config.xml:ro
      - ./config/log4j-config.xml:/kaazing-gateway/conf/log4j-config.xml:ro
    ports:
      - "6661:6661"
      - "8881:8881"

    networks:
      kwic-net:

  server-a:
    image: kaazing/enterprise-gateway:5.7.0
    environment:
      GATEWAY_OPTS: "-Dservice-hostname=server-a -Dservice-port=5551"
    volumes:
      - ./config/echo-server-config.xml:/kaazing-gateway/conf/gateway-config.xml:ro
    networks:
      kwic-net:

  server-b:
    image: kaazing/enterprise-gateway:5.7.0
    environment:
      GATEWAY_OPTS: "-Dservice-hostname=server-b -Dservice-port=6661"
    volumes:
      - ./config/echo-server-config.xml:/kaazing-gateway/conf/gateway-config.xml:ro
    networks:
      kwic-net:

  server-c:
    image: kaazing/enterprise-gateway:5.7.0
    environment:
      GATEWAY_OPTS: "-Dservice-hostname=server-c -Dservice-port=7771"
    volumes:
      - ./config/echo-server-config.xml:/kaazing-gateway/conf/gateway-config.xml:ro
    networks:
      kwic-net:

  server-d:
    image: kaazing/enterprise-gateway:5.7.0
    environment:
      GATEWAY_OPTS: "-Dservice-hostname=server-d -Dservice-port=8881"
    volumes:
      - ./config/echo-server-config.xml:/kaazing-gateway/conf/gateway-config.xml:ro
    networks:
      kwic-net:

networks:
  kwic-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/16
          gateway: 172.31.0.1
